[versions]

targetSdk = "34"

kotlin = "2.0.0-RC2"
google-ksp = "2.0.0-RC2-1.0.20"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization = "1.6.3"

androidx-activity = "1.9.0"
androidx-credentials = "1.2.2"
androidx-datastore = "1.1.1"
androidx-lifecycle = "2.7.0"
androidx-navigation = "2.7.7"
androidx-paging = "3.2.1"
androidx-room = "2.6.1"
androidx-work = "2.9.0"

google-dagger = "2.51.1"
android-gradle = "8.4.0"

detekt = "1.23.6"
mikepenz-aboutlibraries = "11.1.4"
koin = "3.5.6"
compose-destinations = "2.1.0-beta03"
junit = "1.1.5"
roborazzi = "1.13.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
ben-manes-versions = "com.github.ben-manes.versions:0.51.0"
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }
mikepenz-aboutlibraries-plugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "mikepenz-aboutlibraries" }
dependency-graph-generator = "com.vanniktech.dependency.graph.generator:0.8.0"
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
grgit = "org.ajoberstar.grgit.service:5.2.2"
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
dokka = "org.jetbrains.dokka:1.9.20"
[libraries]
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
roborazzi-junitRule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "google-ksp" }
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compose-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.20" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.7" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-biometric = "androidx.biometric:biometric:1.2.0-alpha05"

androidx-browser = "androidx.browser:browser:1.8.0"

androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"

androidx-compose-bom = "androidx.compose:compose-bom:2024.05.00"
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-testJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.3.0-alpha06" }
androidx-compose-material3-adaptiveLayout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version = "1.0.0-alpha12" }
androidx-compose-material3-adaptiveNavigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version = "1.0.0-alpha12" }
androidx-compose-material3-adaptiveNavigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version = "1.0.0-alpha07" }

androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidx-credentials" }
androidx-credentials-playServicesAuth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidx-credentials" }

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }

androidx-documentfile = "androidx.documentfile:documentfile:1.0.1"

androidx-exifinterface = "androidx.exifinterface:exifinterface:1.3.7"

androidx-hilt-compiler = "androidx.hilt:hilt-compiler:1.2.0"
androidx-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-hilt-work = "androidx.hilt:hilt-work:1.2.0"

androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-window = { module = "androidx.window:window-core", version = "1.3.0-beta02" }

androidx-startup-runtime = "androidx.startup:startup-runtime:1.1.1"

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
google-android-play-feature-delivery-ktx = "com.google.android.play:feature-delivery-ktx:2.1.0"
google-android-play-review-ktx = "com.google.android.play:review-ktx:2.0.1"
google-android-billingclient-BillingKtx = "com.android.billingclient:billing-ktx:6.2.1"
google-code-gson = "com.google.code.gson:gson:2.10.1"
google-guava = "com.google.guava:guava:33.1.0-jre"
google-android-gms-play-services-auth = "com.google.android.gms:play-services-auth:21.1.0"
google-api-client-android = "com.google.api-client:google-api-client-android:2.4.1"
google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20240327-2.0.0"

squareup-leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.14"
dropbox-androidSdk = "com.dropbox.core:dropbox-android-sdk:6.1.0"

coil = "io.coil-kt:coil:2.6.0"
coil-compose = "io.coil-kt:coil-compose:2.6.0"
jcifs-ng = "eu.agno3.jcifs:jcifs-ng:2.1.10"
github-omicronapps-SevenZipJBinding4Android = "com.github.omicronapps:7-Zip-JBinding-4Android:Release-16.02-2.02"

artifex-mupdf-fitz = "com.artifex.mupdf:fitz:1.24.0"
squareup-logcat = "com.squareup.logcat:logcat:0.1"
fasterxml-jackson-core = "com.fasterxml.jackson.core:jackson-core:2.17.0"

google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger" }

junit = "junit:junit:4.13.2"
box-java-sdk = "com.box:box-java-sdk:4.8.0"

microsoft-identity-client-msal = "com.microsoft.identity.client:msal:5.3.0"
microsoft-graph = "com.microsoft.graph:microsoft-graph:6.7.0"

androidx-test-core-ktx = "androidx.test:core-ktx:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"

androidx-test-ext-junitKtx = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"

androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
robolectric = "org.robolectric:robolectric:4.12.1"

mikepenz-aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "mikepenz-aboutlibraries" }
nlopez-compose-rules-detekt = "io.nlopez.compose.rules:detekt:0.3.20"
arturbosch-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
arturbosch-detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidxCompose = { group = "io.insert-koin", name = "koin-compose" }
koin-androidxWorkmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }

compose-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destinations" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

[bundles]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx", "androidx-room-paging"]
