[versions]

android-compile-sdk = "33"
android-min-sdk = "28"
android-target-sdk = "33"
android-buildtools = "33.0.2"

kotlin = "1.8.10"
google-ksp = "1.8.10-1.0.9"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.1"

androidx-datastore = "1.0.0"
androidx-lifecycle = "2.5.1"
androidx-navigation = "2.6.0-alpha06"
androidx-paging = "3.1.1"
androidx-room = "2.5.0"
androidx-work = "2.8.0"

dagger-hilt-android = "2.45"

android-gradle = "7.4.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
ben-manes-versions = "com.github.ben-manes.versions:0.46.0"
dagger-hilt-android = { id = "dagger.hilt.android.plugin", version.ref = "dagger-hilt-android" }
aboutlibraries-plugin = "com.mikepenz.aboutlibraries.plugin:10.6.1"
dependency-graph-generator = "com.vanniktech.dependency.graph.generator:0.8.0"
grgit = "org.ajoberstar.grgit:5.0.0"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger-hilt-android" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }

androidx-activity = "androidx.activity:activity:1.6.1"

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-biometric = "androidx.biometric:biometric:1.2.0-alpha05"

androidx-browser = "androidx.browser:browser:1.5.0"

androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"

androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.2.0"

androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.0"

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx.datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx.datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx.datastore" }

androidx-documentfile = "androidx.documentfile:documentfile:1.0.1"

androidx-exifinterface = "androidx.exifinterface:exifinterface:1.3.6"

androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.5.5"

androidx-hilt-compiler = "androidx.hilt:hilt-compiler:1.0.0"
androidx-hilt-navigation-fragment = "androidx.hilt:hilt-navigation-fragment:1.0.0"
androidx-hilt-work = "androidx.hilt:hilt-work:1.0.0"

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }

androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.0"

androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"

androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0-rc01"

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }

androidx-startup-runtime = "androidx.startup:startup-runtime:1.1.1"

androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.1.0-beta01"

androidx-window = "androidx.window:window:1.0.0"

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

google-android-play-feature-delivery-ktx = "com.google.android.play:feature-delivery-ktx:2.0.1"
google-code-gson = "com.google.code.gson:gson:2.10.1"
google-guava = "com.google.guava:guava:31.1-jre"
google-material = "com.google.android.material:material:1.8.0"
google-android-gms-play-services-auth = "com.google.android.gms:play-services-auth:20.4.1"
google-api-client-android = "com.google.api-client:google-api-client-android:2.2.0"
google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20230212-2.0.0"
google-http-client-gson = "com.google.http-client:google-http-client-gson:1.42.3"

squareup-leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.10"
dropbox-core-sdk = "com.dropbox.core:dropbox-core-sdk:5.4.4"

coil = "io.coil-kt:coil:2.2.2"
coil-base = "io.coil-kt:coil-base:2.2.2"
jcifs-ng = "eu.agno3.jcifs:jcifs-ng:2.1.9"
slf4j-android = "org.slf4j:slf4j-android:1.7.36"
sorrowblue-binding-ktx = "com.sorrowblue.jetpack:binding-ktx:3.0.5"
github-omicronapps-SevenZipJBinding4Android = "com.github.omicronapps:7-Zip-JBinding-4Android:Release-16.02-2.02"

artifex-mupdf-fitz = "com.artifex.mupdf:fitz:1.21.0"
squareup-logcat = "com.squareup.logcat:logcat:0.1"
chrisbanes-insetter = "dev.chrisbanes.insetter:insetter-dbx:0.6.1"

dagger-hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt-android" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt-android" }

junit = "junit:junit:4.13.2"
box-java-sdk = "com.box:box-java-sdk:4.0.0"

microsoft-identity-client-msal = "com.microsoft.identity.client:msal:4.2.0"
microsoft-graph = "com.microsoft.graph:microsoft-graph:5.47.0"

androidx-test-core-ktx = "androidx.test:core-ktx:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"

androidx-test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"

androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
robolectric = "org.robolectric:robolectric:4.9.2"

[bundles]
androidx-instrumented-tests = ["androidx-test-core-ktx", "androidx-test-runner", "androidx-test-rules", "androidx-test-ext-junit-ktx", "androidx-test-ext-truth"]
androidx-lifecycle = ["androidx-lifecycle-livedata-ktx", "androidx-lifecycle-viewmodel-ktx"]
androidx-navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx", "androidx-navigation-dynamic-features-fragment"]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx", "androidx-room-paging"]
