[versions]

targetSdk = "34"

kotlin = "1.9.20"
google-ksp = "1.9.10-1.0.13"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.0"

androidx-datastore = "1.0.0"
androidx-lifecycle = "2.6.2"
androidx-navigation = "2.7.5"
androidx-paging = "3.2.1"
androidx-room = "2.6.0"
androidx-work = "2.8.1"

androidx-compose-compiler = "1.5.3"

google-dagger = "2.48.1"
android-gradle = "8.1.2"

mikepenz-aboutlibraries = "10.9.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
ben-manes-versions = "com.github.ben-manes.versions:0.49.0"
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }
mikepenz-aboutlibraries-plugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "mikepenz-aboutlibraries" }
dependency-graph-generator = "com.vanniktech.dependency.graph.generator:0.8.0"
arturbosch-detekt = "io.gitlab.arturbosch.detekt:1.23.1"
grgit = "org.ajoberstar.grgit:5.2.1"

[libraries]
twitter-compose-rules-detekt = "com.twitter.compose.rules:detekt:0.0.26"
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.6" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }

androidx-activity-ktx = "androidx.activity:activity-ktx:1.8.0"

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-biometric = "androidx.biometric:biometric:1.2.0-alpha05"

androidx-browser = "androidx.browser:browser:1.6.0"

androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"

androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.2.0"

androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"

androidx-compose-bom = "androidx.compose:compose-bom:2023.10.01"
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }

androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.2.0-alpha10" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }

androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx.datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx.datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx.datastore" }

androidx-documentfile = "androidx.documentfile:documentfile:1.0.1"

androidx-exifinterface = "androidx.exifinterface:exifinterface:1.3.6"

androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.6.1"

androidx-hilt-compiler = "androidx.hilt:hilt-compiler:1.1.0"
androidx-hilt-navigation-fragment = "androidx.hilt:hilt-navigation-fragment:1.1.0"
androidx-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.1.0"
androidx-hilt-work = "androidx.hilt:hilt-work:1.1.0"

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }

androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.1"

androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"

androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.1"

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }

androidx-startup-runtime = "androidx.startup:startup-runtime:1.1.1"

androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.1.0-beta02"

androidx-window = "androidx.window:window:1.1.0"

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
google-accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version = "0.32.0" }
google-android-play-feature-delivery-ktx = "com.google.android.play:feature-delivery-ktx:2.1.0"
google-android-play-review-ktx = "com.google.android.play:review-ktx:2.0.1"
google-code-gson = "com.google.code.gson:gson:2.10.1"
google-guava = "com.google.guava:guava:32.1.3-jre"
google-material = "com.google.android.material:material:1.10.0"
google-android-gms-play-services-auth = "com.google.android.gms:play-services-auth:20.7.0"
google-api-client-android = "com.google.api-client:google-api-client-android:2.2.0"
google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20230822-2.0.0"
google-http-client-gson = "com.google.http-client:google-http-client-gson:1.43.3"

squareup-leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.12"
dropbox-core-sdk = "com.dropbox.core:dropbox-core-sdk:5.4.6"

coil = "io.coil-kt:coil:2.5.0"
coil-base = "io.coil-kt:coil-base:2.5.0"
coil-compose = "io.coil-kt:coil-compose:2.5.0"
jcifs-ng = "eu.agno3.jcifs:jcifs-ng:2.1.9"
slf4j-android = "org.slf4j:slf4j-android:1.7.36"
sorrowblue-binding-ktx = "com.sorrowblue.jetpack:binding-ktx:3.0.5"
github-omicronapps-SevenZipJBinding4Android = "com.github.omicronapps:7-Zip-JBinding-4Android:Release-16.02-2.02"

artifex-mupdf-fitz = "com.artifex.mupdf:fitz:1.23.4"
squareup-logcat = "com.squareup.logcat:logcat:0.1"
chrisbanes-insetter = "dev.chrisbanes.insetter:insetter-dbx:0.6.1"
fasterxml-jackson-core = "com.fasterxml.jackson.core:jackson-core:2.15.3"

google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger" }

junit = "junit:junit:4.13.2"
box-java-sdk = "com.box:box-java-sdk:4.6.0"

microsoft-identity-client-msal = "com.microsoft.identity.client:msal:4.9.0"
microsoft-graph = "com.microsoft.graph:microsoft-graph:5.75.0"

androidx-test-core-ktx = "androidx.test:core-ktx:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"

androidx-test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"

androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
robolectric = "org.robolectric:robolectric:4.11.1"

mikepenz-aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "mikepenz-aboutlibraries" }


[bundles]
androidx-instrumented-tests = ["androidx-test-core-ktx", "androidx-test-runner", "androidx-test-rules", "androidx-test-ext-junit-ktx", "androidx-test-ext-truth"]
androidx-lifecycle = ["androidx-lifecycle-livedata-ktx"]
androidx-navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx", "androidx-navigation-dynamic-features-fragment"]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx", "androidx-room-paging"]
androidx-compose = ["androidx-compose-material3", "androidx-compose-ui-tooling-preview", "androidx-compose-material-icons-extended", "androidx-compose-material", "androidx-compose-material3-windowSizeClass", "androidx-compose-ui-util"]
androidx-compose-debug = ["androidx-compose-ui-tooling", "androidx-compose-ui-test-manifest"]
