comments:
  active: true

complexity:
  active: false

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

formatting:
  active: true
  ImportOrdering:
    active: true
    layout: '*,^'
  TrailingCommaOnDeclarationSite:
    active: true
  MaximumLineLength:
    active: false

naming:
  active: true
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

  MatchingDeclarationName:
    active: false

performance:
  active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: false

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewComic'
      - 'PreviewMobile'
      - 'PreviewTablet'

# https://mrmans0n.github.io/compose-rules/detekt/
Compose:
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals:
      - 'LocalDimension'
      - 'LocalWindowSize'
    # You can optionally define a list of CompositionLocals that are allowed here
    # allowedCompositionLocals: LocalSomething,LocalSomethingElse
  ContentEmitterReturningValues:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  DefaultsVisibility:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
    # You can optionally control the visibility of which composables to check for here
    # Possible values are: `only_public`, `public_and_internal` and `all` (default is `only_public`)
    # checkModifiersForVisibility: only_public
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  MutableParams:
    active: true
  ComposableNaming:
    active: true
    # You can optionally disable the checks in this rule for regex matches against the composable name (e.g. molecule presenters)
    # allowedComposableFunctionNames: .*Presenter,.*MoleculePresenter
  ComposableParamOrder:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RememberContentMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
    # You can optionally use this rule on things other than types ending in "ViewModel" or "Presenter" (which are the defaults). You can add your own via a regex here:
    # allowedStateHolderNames: .*ViewModel,.*Presenter
  ViewModelInjection:
    active: true
    # You can optionally add your own ViewModel factories here
    # viewModelFactories: hiltViewModel,potatoViewModel
